// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerFantasy.Models;

#nullable disable

namespace SoccerFantasy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231216143556_Iteration7")]
    partial class Iteration7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("SoccerFantasy.Models.FantasyLeague", b =>
                {
                    b.Property<Guid>("fantasyLeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fantasyLeagueCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("fantasyLeagueId");

                    b.ToTable("fantasyLeagues");
                });

            modelBuilder.Entity("SoccerFantasy.Models.FantasyTeam", b =>
                {
                    b.Property<Guid>("fantasyTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("current_round_points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("totalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("fantasyTeamId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("FantasyTeams");
                });

            modelBuilder.Entity("SoccerFantasy.Models.FantasyTeamLeague", b =>
                {
                    b.Property<Guid>("FantasyTeamLeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("fantasyLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("fantasyTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FantasyTeamLeagueId");

                    b.HasIndex("fantasyLeagueId");

                    b.HasIndex("fantasyTeamId");

                    b.ToTable("fantasyTeamLeagues");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Goal", b =>
                {
                    b.Property<Guid>("goalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("goalScorerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("matchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("matchId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("minute")
                        .HasColumnType("INTEGER");

                    b.HasKey("goalId");

                    b.HasIndex("goalScorerId");

                    b.HasIndex("matchId");

                    b.HasIndex("matchId1");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Match", b =>
                {
                    b.Property<Guid>("matchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("awayPossesion")
                        .HasColumnType("TINYINT UNSIGNED");

                    b.Property<string>("awayTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("awayTotalShots")
                        .HasColumnType("TINYINT UNSIGNED");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("homePossesion")
                        .HasColumnType("TINYINT UNSIGNED");

                    b.Property<string>("homeTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("homeTotalShots")
                        .HasColumnType("TINYINT UNSIGNED");

                    b.Property<bool>("matchPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("minute")
                        .HasColumnType("INTEGER");

                    b.HasKey("matchId");

                    b.HasIndex("awayTeamName");

                    b.HasIndex("homeTeamName");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Player", b =>
                {
                    b.Property<Guid>("playerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("appearances")
                        .HasColumnType("INTEGER");

                    b.Property<int>("assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cleanSheets")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("fantasyTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("fantasy_round_points")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("matchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("matchId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("matchId2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("matchId3")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nationCSS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nationURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("playerImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("teamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("playerId");

                    b.HasIndex("fantasyTeamId");

                    b.HasIndex("matchId");

                    b.HasIndex("matchId1");

                    b.HasIndex("matchId2");

                    b.HasIndex("matchId3");

                    b.HasIndex("teamName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Team", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("clubLogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("gamesDraw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("gamesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("gamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("gamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goalDiff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("points")
                        .HasColumnType("INTEGER");

                    b.HasKey("name");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("SoccerFantasy.Models.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SoccerFantasy.Models.FantasyTeam", b =>
                {
                    b.HasOne("SoccerFantasy.Models.User", "user")
                        .WithOne("fantasyTeam")
                        .HasForeignKey("SoccerFantasy.Models.FantasyTeam", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SoccerFantasy.Models.FantasyTeamLeague", b =>
                {
                    b.HasOne("SoccerFantasy.Models.FantasyLeague", "FantasyLeague")
                        .WithMany("FantasyTeamLeagues")
                        .HasForeignKey("fantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerFantasy.Models.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyTeamLeagues")
                        .HasForeignKey("fantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyLeague");

                    b.Navigation("FantasyTeam");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Goal", b =>
                {
                    b.HasOne("SoccerFantasy.Models.Player", "goalScorer")
                        .WithMany("goals")
                        .HasForeignKey("goalScorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerFantasy.Models.Match", "match")
                        .WithMany("homeGoals")
                        .HasForeignKey("matchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerFantasy.Models.Match", null)
                        .WithMany("awayGoals")
                        .HasForeignKey("matchId1");

                    b.Navigation("goalScorer");

                    b.Navigation("match");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Match", b =>
                {
                    b.HasOne("SoccerFantasy.Models.Team", "awayTeam")
                        .WithMany()
                        .HasForeignKey("awayTeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerFantasy.Models.Team", "homeTeam")
                        .WithMany()
                        .HasForeignKey("homeTeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("awayTeam");

                    b.Navigation("homeTeam");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Player", b =>
                {
                    b.HasOne("SoccerFantasy.Models.FantasyTeam", null)
                        .WithMany("players")
                        .HasForeignKey("fantasyTeamId");

                    b.HasOne("SoccerFantasy.Models.Match", null)
                        .WithMany("awayStartingPlayers")
                        .HasForeignKey("matchId");

                    b.HasOne("SoccerFantasy.Models.Match", null)
                        .WithMany("awaySubPlayers")
                        .HasForeignKey("matchId1");

                    b.HasOne("SoccerFantasy.Models.Match", null)
                        .WithMany("homeStartingPlayers")
                        .HasForeignKey("matchId2");

                    b.HasOne("SoccerFantasy.Models.Match", null)
                        .WithMany("homeSubPlayers")
                        .HasForeignKey("matchId3");

                    b.HasOne("SoccerFantasy.Models.Team", "teamRef")
                        .WithMany("players")
                        .HasForeignKey("teamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("teamRef");
                });

            modelBuilder.Entity("SoccerFantasy.Models.FantasyLeague", b =>
                {
                    b.Navigation("FantasyTeamLeagues");
                });

            modelBuilder.Entity("SoccerFantasy.Models.FantasyTeam", b =>
                {
                    b.Navigation("FantasyTeamLeagues");

                    b.Navigation("players");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Match", b =>
                {
                    b.Navigation("awayGoals");

                    b.Navigation("awayStartingPlayers");

                    b.Navigation("awaySubPlayers");

                    b.Navigation("homeGoals");

                    b.Navigation("homeStartingPlayers");

                    b.Navigation("homeSubPlayers");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Player", b =>
                {
                    b.Navigation("goals");
                });

            modelBuilder.Entity("SoccerFantasy.Models.Team", b =>
                {
                    b.Navigation("players");
                });

            modelBuilder.Entity("SoccerFantasy.Models.User", b =>
                {
                    b.Navigation("fantasyTeam")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
